name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.1.0
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  freezed_annotation: ^2.0.1
  cupertino_icons: ^1.0.4
  wakelock: ^0.5.6
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.8.5+3
  visibility_detector: ^0.3.0
  path_provider: ^2.0.8
  collection: ^1.15.0
  dartx: ^1.1.0
  get_it: ^7.2.0
  after_layout: ^1.1.0
  xml: ^5.3.1
  brightness_volume: ^1.0.3
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  # event_bus:
  #   path: ../dart-event-bus

dev_dependencies:
  # lint: ^1.8.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^2.0.2
  build_runner: ^2.1.10

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin